version: '3'

services:
  products-store-db:
    container_name: products-store-db
    image: postgres:16.2
    restart: always
    # this local path is the local volume from the container, for persistent data
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: YourStrongPostgresPassword
      POSTGRES_USER: postgres
      POSTGRES_DB: products-store1-db
